apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: argocd-demo
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/ArulChinnappa12112004/argocd-demo.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true